// assets/styles/setting.styles.ts
import { StyleSheet } from "react-native";
import { ThemeType } from "../../themes/theme";
const createSettingStyles = (colors: ThemeType) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      // paddingHorizontal: 20,
    },
    backButton: {
      marginTop: 40,
      marginBottom: 10,
      alignSelf: "flex-start",
    },
    header: {
      fontSize: 28,
      fontWeight: "bold",
      marginBottom: 20,
      color: colors.textDark,
    },
    section: {
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.textPrimary,
      marginBottom: 10,
    },
    card: {
      backgroundColor: colors.cardBackground,
      borderRadius: 16,
      padding: 16,
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    cardRow: {
      backgroundColor: colors.cardBackground,
      borderRadius: 16,
      padding: 16,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    row: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    rowBetween: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginVertical: 8,
    },
    label: {
      fontSize: 14,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    value: {
      fontSize: 16,
      color: colors.textPrimary,
      marginTop: 4,
    },
    input: {
      fontSize: 16,
      color: colors.textPrimary,
      backgroundColor: colors.inputBackground,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 10,
      marginTop: 4,
      width: "100%",
      paddingRight: 40,
    },
    inputWrapper: {
      position: "relative",
      marginTop: 16,
    },
    inputPassword: {
      fontSize: 16,
      color: colors.textPrimary,
      backgroundColor: colors.inputBackground,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 10,
      width: "100%",
      paddingRight: 40,
    },
    eyeIcon: {
      position: "absolute",
      right: 12,
      top: "50%",
      transform: [{ translateY: -10 }],
      zIndex: 1,
    },
    createPassword: {
      fontSize: 16,
      fontWeight: "bold",
      color: colors.textPrimary,
    },
    logoutBtn: {
      backgroundColor: colors.primary,
      paddingVertical: 12,
      borderRadius: 30,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginTop: 20,
    },
    logoutText: {
      color: colors.white,
      fontWeight: "bold",
      marginLeft: 16,
    },
    deleteBtn: {
      marginTop: 16,
      alignSelf: "center",
    },
    deleteText: {
      color: "red",
      fontWeight: "500",
      fontSize: 14,
    },
    modalContainer: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    modalContent: {
      width: "100%",
      backgroundColor: colors.white,
      borderRadius: 20,
      padding: 20,
      shadowColor: "#000",
      shadowOpacity: 0.25,
      shadowRadius: 10,
      elevation: 10,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 16,
      color: colors.textPrimary,
      textAlign: "center",
    },
    modalActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      marginTop: 24,
    },
    cancelButton: {
      marginRight: 12,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: colors.border,
    },
    cancelText: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.textPrimary,
    },
    inputIcon: { marginRight: 10 },
    saveButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: colors.primary,
    },
    saveText: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.white,
    },
  });

export default createSettingStyles;
